version: "3.8"

services:
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=fpl_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=coderslab
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - db_network
      - web_network
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/opt/services/app/static/
    depends_on:
      - web
    networks:
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data: