# Generated by Django 3.0.4 on 2020-04-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('form', models.TextField(max_length=64, null=True)),
                ('loss', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('played', models.IntegerField()),
                ('points', models.IntegerField()),
                ('position', models.IntegerField()),
                ('short_name', models.CharField(max_length=4)),
                ('strength', models.IntegerField()),
                ('team_division', models.TextField(null=True)),
                ('win', models.IntegerField()),
                ('strength_overall_home', models.IntegerField()),
                ('strength_overall_away', models.IntegerField()),
                ('strength_attack_home', models.IntegerField()),
                ('strength_attack_away', models.IntegerField()),
                ('strength_defence_home', models.IntegerField()),
                ('strength_defence_away', models.IntegerField()),
            ],
        ),
    ]
