# Generated by Django 3.0.4 on 2020-04-11 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('news', models.TextField(max_length=256)),
                ('news_added', models.DateTimeField(null=True)),
                ('minutes', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('clean_sheets', models.IntegerField()),
                ('goals_conceded', models.IntegerField()),
                ('own_goals', models.IntegerField()),
                ('penalties_saved', models.IntegerField()),
                ('penalties_missed', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('chance_of_playing_next_round', models.IntegerField(null=True)),
                ('chance_of_playing_this_round', models.IntegerField(null=True)),
                ('cost_change_event', models.IntegerField()),
                ('cost_change_event_fall', models.IntegerField()),
                ('cost_change_start', models.IntegerField()),
                ('dreamteam_count', models.IntegerField()),
                ('ep_next', models.FloatField()),
                ('ep_this', models.FloatField()),
                ('event_points', models.IntegerField()),
                ('form', models.FloatField()),
                ('in_dreamteam', models.BooleanField()),
                ('now_cost', models.FloatField()),
                ('points_per_game', models.FloatField()),
                ('selected_by_percent', models.FloatField(null=True)),
                ('special', models.BooleanField(null=True)),
                ('total_points', models.IntegerField(null=True)),
                ('value_form', models.FloatField()),
                ('value_season', models.FloatField()),
                ('bonus', models.IntegerField()),
                ('bps', models.IntegerField()),
                ('influence', models.FloatField()),
                ('creativity', models.FloatField()),
                ('threat', models.FloatField()),
                ('ict_index', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('name_short', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=4)),
                ('position', models.SmallIntegerField()),
                ('played', models.SmallIntegerField()),
                ('win', models.SmallIntegerField()),
                ('draw', models.SmallIntegerField()),
                ('loss', models.SmallIntegerField()),
                ('points', models.SmallIntegerField()),
                ('form', models.TextField(max_length=8, null=True)),
                ('strength', models.SmallIntegerField()),
                ('strength_overall_home', models.SmallIntegerField()),
                ('strength_overall_away', models.SmallIntegerField()),
                ('strength_attack_home', models.SmallIntegerField()),
                ('strength_attack_away', models.SmallIntegerField()),
                ('strength_defence_home', models.SmallIntegerField()),
                ('strength_defence_away', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('def1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def1', to='fantasy_pl.Player')),
                ('def2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def2', to='fantasy_pl.Player')),
                ('def3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def3', to='fantasy_pl.Player')),
                ('def4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def4', to='fantasy_pl.Player')),
                ('fwd1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fwd1', to='fantasy_pl.Player')),
                ('fwd2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fwd2', to='fantasy_pl.Player')),
                ('gkp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gkp', to='fantasy_pl.Player')),
                ('mdf1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdf1', to='fantasy_pl.Player')),
                ('mdf2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdf2', to='fantasy_pl.Player')),
                ('mdf3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdf3', to='fantasy_pl.Player')),
                ('mdf4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdf4', to='fantasy_pl.Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_pl.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_pl.Team'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
