# Generated by Django 3.0.4 on 2020-04-03 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('chance_of_playing_next_round', models.IntegerField()),
                ('chance_of_playing_this_round', models.IntegerField()),
                ('cost_change_event', models.IntegerField()),
                ('cost_change_event_fall', models.IntegerField()),
                ('cost_change_start', models.IntegerField()),
                ('dreamteam_count', models.IntegerField()),
                ('element_type', models.IntegerField()),
                ('ep_next', models.FloatField()),
                ('ep_this', models.FloatField()),
                ('event_points', models.IntegerField()),
                ('first_name', models.CharField(max_length=16)),
                ('form', models.FloatField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_dreamteam', models.BooleanField()),
                ('news', models.TextField(max_length=256)),
                ('news_added', models.DateTimeField()),
                ('now_cost', models.IntegerField()),
                ('points_per_game', models.FloatField()),
                ('second_name', models.CharField(max_length=16)),
                ('value_form', models.FloatField()),
                ('value_season', models.FloatField()),
                ('minutes', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('clean_sheets', models.IntegerField()),
                ('goals_conceded', models.IntegerField()),
                ('own_goals', models.IntegerField()),
                ('penalties_saved', models.IntegerField()),
                ('penalties_missed', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('bps', models.IntegerField()),
                ('influence', models.FloatField()),
                ('creativity', models.FloatField()),
                ('threat', models.FloatField()),
                ('ict_index', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_pl.Team')),
            ],
        ),
    ]
