# Generated by Django 3.0.4 on 2020-04-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0002_auto_20200414_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_pl.Position'),
        ),
    ]
