# Generated by Django 3.0.4 on 2020-04-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0002_auto_20200411_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='name',
        ),
    ]
