# Generated by Django 3.0.4 on 2020-04-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chance_of_playing_next_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='chance_of_playing_this_round',
            field=models.IntegerField(null=True),
        ),
    ]
