# Generated by Django 3.0.4 on 2020-04-15 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy_pl', '0003_auto_20200414_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='defb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defb', to='fantasy_pl.Player'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='fwdb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fwdb', to='fantasy_pl.Player'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='gkpb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gkpb', to='fantasy_pl.Player'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='mdfb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfdb', to='fantasy_pl.Player'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
