# Generated by Django 3.0.4 on 2020-04-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0004_auto_20200403_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='second_name',
            field=models.CharField(max_length=32),
        ),
    ]
