# Generated by Django 3.0.4 on 2020-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0004_auto_20200415_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userteam',
            name='creativity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userteam',
            name='dt_apps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userteam',
            name='influence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userteam',
            name='novelty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userteam',
            name='points_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userteam',
            name='threat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userteam',
            name='total_points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
