# Generated by Django 3.0.4 on 2020-04-04 18:50

from django.db import migrations, models
import fantasy_pl.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0005_auto_20200403_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('name_short', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='element_type',
            field=models.IntegerField(verbose_name=fantasy_pl.models.Position),
        ),
    ]
