# Generated by Django 3.0.4 on 2020-04-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0005_auto_20200416_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.SmallIntegerField()),
                ('total_points', models.SmallIntegerField()),
                ('was_home', models.BooleanField()),
                ('kickoff_team', models.DateTimeField()),
                ('team_h_score', models.SmallIntegerField()),
                ('team_a_score', models.SmallIntegerField()),
                ('round', models.SmallIntegerField()),
                ('minutes', models.SmallIntegerField()),
                ('goal_scored', models.SmallIntegerField()),
                ('assists', models.SmallIntegerField()),
                ('clean_sheets', models.SmallIntegerField()),
                ('goals_conceded', models.SmallIntegerField()),
                ('own_goals', models.SmallIntegerField()),
                ('penalty_saved', models.SmallIntegerField()),
                ('penalty_missed', models.SmallIntegerField()),
                ('yellow_cards', models.SmallIntegerField()),
                ('red_cards', models.SmallIntegerField()),
                ('saves', models.SmallIntegerField()),
                ('bonus', models.SmallIntegerField()),
                ('bps', models.SmallIntegerField()),
                ('influence', models.FloatField()),
                ('creativity', models.FloatField()),
                ('threat', models.FloatField()),
                ('ict_index', models.FloatField()),
                ('value', models.SmallIntegerField()),
                ('transfer_balance', models.SmallIntegerField()),
                ('selected', models.IntegerField()),
                ('transfer_in', models.SmallIntegerField()),
                ('transfer_out', models.SmallIntegerField()),
                ('opponent_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasy_pl.Team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_pl.Player')),
            ],
            options={
                'unique_together': {('player', 'fixture')},
            },
        ),
    ]
