# Generated by Django 3.0.4 on 2020-04-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0006_auto_20200404_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_division',
        ),
        migrations.AlterField(
            model_name='team',
            name='form',
            field=models.TextField(max_length=8, null=True),
        ),
    ]
