# Generated by Django 3.0.4 on 2020-04-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0006_player_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='player_history',
            new_name='PlayerHistory',
        ),
        migrations.RenameField(
            model_name='playerhistory',
            old_name='goal_scored',
            new_name='goals_scored',
        ),
        migrations.RenameField(
            model_name='playerhistory',
            old_name='kickoff_team',
            new_name='kickoff_time',
        ),
    ]
