# Generated by Django 3.0.4 on 2020-04-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0007_auto_20200404_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_pl.Position'),
        ),
    ]
