# Generated by Django 3.0.4 on 2020-04-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0007_auto_20200421_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerhistory',
            old_name='penalty_missed',
            new_name='penalties_missed',
        ),
        migrations.RenameField(
            model_name='playerhistory',
            old_name='penalty_saved',
            new_name='penalties_saved',
        ),
        migrations.RenameField(
            model_name='playerhistory',
            old_name='transfer_balance',
            new_name='transfers_balance',
        ),
        migrations.RenameField(
            model_name='playerhistory',
            old_name='transfer_in',
            new_name='transfers_in',
        ),
        migrations.RenameField(
            model_name='playerhistory',
            old_name='transfer_out',
            new_name='transfers_out',
        ),
    ]
