# Generated by Django 3.0.4 on 2020-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0008_auto_20200421_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhistory',
            name='transfers_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='transfers_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='transfers_out',
            field=models.IntegerField(),
        ),
    ]
