# Generated by Django 3.0.4 on 2020-04-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0008_auto_20200404_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='code',
        ),
    ]
