# Generated by Django 3.0.4 on 2020-04-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0009_remove_team_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='element_type',
            new_name='position',
        ),
    ]
