# Generated by Django 3.0.4 on 2020-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0010_auto_20200405_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='now_cost',
            field=models.FloatField(),
        ),
    ]
