# Generated by Django 3.0.4 on 2020-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0011_auto_20200405_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='selected_by_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='special',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(null=True),
        ),
    ]
