# Generated by Django 3.0.4 on 2020-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0012_auto_20200406_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='draw',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='loss',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='played',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='strength',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='strength_attack_away',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='strength_attack_home',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='strength_defence_away',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='strength_defence_home',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='strength_overall_away',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='strength_overall_home',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='win',
            field=models.SmallIntegerField(),
        ),
    ]
