# Generated by Django 3.0.4 on 2020-04-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_pl', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
